#!/usr/local/bin/python

import sys

from robot_rqt_plugin.my_module import MyPlugin
from rqt_gui.main import Main

plugin = 'robot_rqt_plugin'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
